phone can no longer be none
tekulvw/modularsecurity pull request #179
Opened 2017-07-23 22:28 UTC by gattoej

2017-07-24 00:54 UTC, tekulvw requested changes

2017-07-24 00:54 UTC, tekulvw commented on backend/tests/test_models/test_user.py
> +        "phone_num": ""
This needs to be `"phone_num": None` to actually test the problem

2017-07-25 17:11 UTC, tekulvw approved these changes

2017-07-25 17:13 UTC, JAKeeney approved these changes

2017-07-25 17:13 UTC, merged